
sudo: required
language: generic
services: docker

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino

script:
  # We use the docker image from https://hub.docker.com/r/dxjoke/tectonic-docker/
  # Compiling only main.tex:
  - docker run --mount src=$TRAVIS_BUILD_DIR/Report,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic main.tex"
  - arduino --verify --board arduino:avr:uno $PWD/Code/AlarmCode.ino


deploy:
  provider: releases
  api_key:
    secure: c2VStvGvrfmj4XK4XEOhwThQDOTaTVGBg+KPUhbkpT5kXUnFNqzV3flIZ58Pdv4Ixh/5ePKvfaPbGn1NMPHIRbE7bPSEvkCmAZqONfF6ZpbW358TV2+EVG1TByW7NQhNgQdspwSTyinWDhTxMxsPcymIaE4qQGiVsH0kBoXHidnnK9UYa1O0jCHfagL8mXNbOtgb0pweM7OkDIMYDAGuH+CJXT/IH5umowiKvh5ka43hAa5+24aJTtV+TBYVL2ODIwZo6HPOC0CLSKOSTFxrZASF65YWaXURjUSV3T9Yx4KfGO8ad+l8RsqhwerxfMcl+0mG2RkcGP1BN8tScI153tckByAUaX2X8HbQtDnANT7DTULYh62CESnJDqZreyQw4qCRuTaD/CtBkGnA1JFbRUzxsN5DTo7MxpKFaIutn1MYfU35sLE5Fw3Uc2W6JrjNGdZak9rea4wC+eo0ns+HW5NOgK5q30v/w10NNafBl5Q8vZ1SI9TYbWEL3zreAaqtIpmW6kIGHtSpaDVx/drwtsyBhW9SlAucP8hurEZSuK38DiNgaB/mGtcLdCRDsyB2r7WS+r573L0mAyx0yuzrIX4ZI7G69224xtqaLGxcQeWEqgT5qW8OZcizNwK6PUlGeaUEG/9ddh5BwJZU1qPNA0sq9Z39LnMScAXiUBkAlik=
  file: 
    - Report/main.pdf
  on:
    repo: KerbalJeb/ECE299DesignProject
    branch: Latex-Integration
    draft: true
  skip_cleanup: 'true'
